### ISSUE TITLE
¿Qué estoy haciendo mal?

### ISSUE THREAD

**Issue by rchajin** [julianduque/tv-maze#12]
Buenos días Julian.

Estoy tratando de implementar el api con el código de ejemplo que provees, pero obtengo este error siempre que intento correrlo.

TypeError: callback is not a function
    at /Users/robertochajin/Desarrollo/tv-maze-api/node_modules/tv-maze/lib/client.js:25:5
    at reply (/Users/robertochajin/Desarrollo/tv-maze-api/node_modules/client-request/request.js:74:12)
    at Concat.collect [as callback] (/Users/robertochajin/Desarrollo/tv-maze-api/node_modules/client-request/request.js:88:12)
    at Concat._done (/Users/robertochajin/Desarrollo/tv-maze-api/node_modules/client-request/concat.js:47:19)
    at emitNone (events.js:91:20)
    at Concat.emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:515:14)
    at endWritable (_stream_writable.js:525:3)
    at Concat.Writable.end (_stream_writable.js:490:5)
    at IncomingMessage.onend (_stream_readable.js:511:10)

Quedo atento.

Saludos

**Comment by EmryRosario** [comment]
Pasa la implementación de como lo estás haciendo?
